Added some tests for change_prot
pranav-bhatt/rust_vmmap pull request #4
Opened 2024-10-07 14:26 UTC by ruchjoshi-nyu

testing changing protection for single entry, partial entry and multiple entries

2024-10-07 14:37 UTC, pranav-bhatt requested changes

2024-10-07 14:37 UTC, pranav-bhatt commented on vmmap.rs
> +use std::io;
This file seems to have some issues cause its adding all the lines as new lines. If you're on windows, please ensure you use LF line endings by default instead of CRLF. Once you've done this, request a rereview and I'll take a look again :)

2024-10-07 14:37 UTC, pranav-bhatt commented on vmmap.rs
> +        assert_eq!(entries[0].prot, PROT_READ);
do add comments of expected behaviour/why you are testing for a particular case

2024-10-07 15:13 UTC, ruchjoshi-nyu commented on vmmap.rs
> +use std::io;
Can you check now? It should have been fixed

2024-10-07 15:13 UTC, ruchjoshi-nyu commented on vmmap.rs
> +        assert_eq!(entries[0].prot, PROT_READ);
comments added

2024-10-13 00:41 UTC, pranav-bhatt requested changes

2024-10-13 00:41 UTC, pranav-bhatt commented on vmmap.rs
> +use std::io;
hey, it still doesn't seem fixed

2024-10-16 00:17 UTC, closed without merging